version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - zombie-game-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=gameuser
      - DB_PASSWORD=gamepass
      - DB_NAME=zombie_game
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=development-jwt-secret-key
      - GIN_MODE=release
    depends_on:
      - postgres
      - redis
    networks:
      - zombie-game-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=zombie_game
      - POSTGRES_USER=gameuser
      - POSTGRES_PASSWORD=gamepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - zombie-game-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zombie-game-network

volumes:
  postgres_data:
  redis_data:

networks:
  zombie-game-network:
    driver: bridge